name: sad_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - streamlit=1.31.1
  - pandas=2.1.4
  - numpy=1.24.3
  - plotly=5.18.0
  - scipy=1.11.4
  - openpyxl=3.1.2
  - xlrd=2.0.1
  - pillow=10.0.1
  - reportlab=4.0.8
  - kaleido=0.2.1
  - matplotlib=3.8.2
  - seaborn=0.13.0 