name: sad_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - streamlit=1.32.0
  - pandas=2.2.1
  - numpy=1.26.4
  - plotly=5.19.0
  - scipy=1.12.0
  - openpyxl=3.1.2
  - xlrd=2.0.1
  - pillow=10.2.0
  - reportlab=4.1.0
  - kaleido=0.2.1
  - matplotlib=3.8.3
  - seaborn=0.13.2
  - pip
  - pip:
    - streamlit-option-menu
    - streamlit-extras 